version: "3"
services:
  app:
    environment: 
      - PORT=80
    build: ./app
    volumes:
      - "./app:/app"
    command: bash -c "yarn --no-bin-links && /bin/bash"
    ports:
      - "8080:80"
      - "9229:9229"
    networks:
      - webnet
    stdin_open: true
    tty: true
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongodatabase:/data/db
    ports:
      - "27017:27017"
    networks:
      webnet:
        aliases:
          - mongo
networks:
  webnet:
volumes:
  mongodatabase:
