version: "3"
services:
  app:
    environment: 
      - PORT=80
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=data
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: ./app
    volumes:
      - "./app:/app"
    command: bash -c "yarn --no-bin-links && /bin/bash"
    ports:
      - "8080:80"
      - "9229:9229"
    networks:
      - webnet
    stdin_open: true
    tty: true
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongodatabase:/data/db
    ports:
      - "27017:27017"
    networks:
      webnet:
        aliases:
          - mongo
  redis:
    image: redis
    volumes:
     - redisdatabase:/data
    ports:
      - "6379:6379"
    networks:
      webnet:
        aliases:
          - redis
networks:
  webnet:
volumes:
  mongodatabase:
  redisdatabase:
