version: "3"
services:
  app:
    environment: 
      - PORT=80
    build: ./app
    volumes:
      - "./app:/app"
      - "/app/node_modules"
    ports:
      - "8080:80"
    networks:
      - webnet
networks:
  webnet:
